apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webflux-demo-service
  name: webflux-demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webflux-demo-service
  template:
    metadata:
      labels:
        app: webflux-demo-service
    spec:
      containers:
        - image: 'quay.io/sadema/webflux-demo:1.0.0'
          imagePullPolicy: Always
          name: webflux-demo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webflux-demo-service
  name: webflux-demo-service
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webflux-demo-service
  type: ClusterIP
